#!/usr/bin/env python3
"""Extract a lightweight Lean declaration inventory for TLICA."""
from __future__ import annotations

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
DECL_RE = re.compile(r"^\s*(?:noncomputable\s+)?(?:protected\s+)?(class|structure|inductive|def|abbrev|theorem|lemma|instance|axiom)\s+([^\s:({]+)")

print("# Lean Declaration Inventory")
print()
print("Generated by `scripts/extract_lean_decls.py`.")
print()
print("| Module/File | Kind | Declaration |")
print("|---|---|---|")

for path in sorted((ROOT / "TLICA").rglob("*.lean")) + [ROOT / "TLICA.lean"]:
    if not path.exists():
        continue
    rel = path.relative_to(ROOT)
    for line in path.read_text(encoding="utf-8").splitlines():
        m = DECL_RE.match(line)
        if m:
            kind, name = m.groups()
            print(f"| `{rel}` | `{kind}` | `{name}` |")
