/-
TLICA.TemporalTrajectory — Deterministic profile trajectories.

This module adds the first temporal layer over the verified agency/free-will
apparatus. A trajectory is supplied as indexed profile data; `generatedBy`
records when that data follows the deterministic action-indexed projection.
The module does not assert global trajectory existence, stochastic dynamics, or
phenomenological experience of divergence.
-/

import TLICA.FreeWill
import TLICA.ProfileComparison.Pointwise

namespace TLICA.TemporalTrajectory

open TLICA.Profile
open TLICA.ProfileComparison.Pointwise
open TLICA.Agency
open TLICA.FreeWill
open TLICA.ActionProjection
open TLICA.GeneralActionProjection
open scoped ENNReal

variable {α Act : Type*}

/-- A natural-time indexed sequence of scalar profiles. -/
structure ProfileTrajectory (α : Type*) where
  /-- Profile observed or represented at natural time `n`. -/
  profileAt : ℕ → ScalarProfile α

/-- A natural-time indexed action schedule. -/
structure ActionSchedule (Act : Type*) where
  /-- Action assigned at natural time `n`. -/
  actionAt : ℕ → Act

/-- A supplied trajectory is generated by a supplied schedule when each
    successor profile is the deterministic projection of the previous profile
    under the scheduled action. -/
def generatedBy (ctx : AgencyContext α Act)
    (traj : ProfileTrajectory α) (sched : ActionSchedule Act) : Prop :=
  ∀ n, traj.profileAt (n + 1) =
    generalProjectedProfile ctx.proj (traj.profileAt n) (sched.actionAt n)

/-- Named one-step equation for a generated trajectory. -/
theorem generatedBy_step
    {ctx : AgencyContext α Act} {traj : ProfileTrajectory α}
    {sched : ActionSchedule Act}
    (h : generatedBy ctx traj sched) (n : ℕ) :
    traj.profileAt (n + 1) =
      generalProjectedProfile ctx.proj (traj.profileAt n) (sched.actionAt n) :=
  h n

/-- Direct projected-profile spelling of the generated one-step equation. -/
theorem generatedBy_step_projectedProfile
    {ctx : AgencyContext α Act} {traj : ProfileTrajectory α}
    {sched : ActionSchedule Act}
    (h : generatedBy ctx traj sched) (n : ℕ) :
    traj.profileAt (n + 1) =
      projectedProfile ctx.proj (traj.profileAt n) (sched.actionAt n) := by
  rw [generatedBy_step h n, generalProjectedProfile_eq_projectedProfile]

/-- Future MSI contents of the scheduled branch at a time along a trajectory. -/
def trajectoryFutureContents (ctx : AgencyContext α Act)
    (traj : ProfileTrajectory α) (sched : ActionSchedule Act) (n : ℕ) :
    Set α :=
  branchFutureContents ctx (traj.profileAt n) (sched.actionAt n)

/-- `trajectoryFutureContents` unfolds to the branch-future contents at the
    scheduled action. -/
theorem trajectoryFutureContents_eq_branchFutureContents
    (ctx : AgencyContext α Act)
    (traj : ProfileTrajectory α) (sched : ActionSchedule Act) (n : ℕ) :
    trajectoryFutureContents ctx traj sched n =
      branchFutureContents ctx (traj.profileAt n) (sched.actionAt n) :=
  rfl

/-- Union-domain profile distance between adjacent times. -/
noncomputable def stepUnionDistance (traj : ProfileTrajectory α) (n : ℕ) :
    ℝ≥0∞ :=
  dInfUnion (traj.profileAt n) (traj.profileAt (n + 1))

/-- Adjacent union-domain distance is nonnegative by codomain. -/
theorem stepUnionDistance_nonneg (traj : ProfileTrajectory α) (n : ℕ) :
    0 ≤ stepUnionDistance traj n :=
  bot_le

/-- Adjacent union-domain distance is bounded by the profile-comparison bound. -/
theorem stepUnionDistance_le_one (traj : ProfileTrajectory α) (n : ℕ) :
    stepUnionDistance traj n ≤ 1 := by
  unfold stepUnionDistance
  exact dInfUnion_le_one _ _

/-- Shared-domain profile distance between adjacent times. -/
noncomputable def stepSharedDistance (traj : ProfileTrajectory α) (n : ℕ) :
    ℝ≥0∞ :=
  dInfShared (traj.profileAt n) (traj.profileAt (n + 1))

/-- Uniform stepwise temporal stability measured by union-domain distance. -/
def unionStepStable (traj : ProfileTrajectory α) (ε : ℝ≥0∞) : Prop :=
  ∀ n, stepUnionDistance traj n ≤ ε

/-- Uniform step stability gives the stated bound at each step. -/
theorem unionStepStable_step_le
    {traj : ProfileTrajectory α} {ε : ℝ≥0∞}
    (h : unionStepStable traj ε) (n : ℕ) :
    stepUnionDistance traj n ≤ ε :=
  h n

/-- Eventual stepwise temporal stability measured by union-domain distance. -/
def eventuallyUnionStepStable
    (traj : ProfileTrajectory α) (ε : ℝ≥0∞) (N : ℕ) : Prop :=
  ∀ n, N ≤ n → stepUnionDistance traj n ≤ ε

/-- Eventual step stability persists if the start index is moved later. -/
theorem eventuallyUnionStepStable_of_le_start
    {traj : ProfileTrajectory α} {ε : ℝ≥0∞} {N M : ℕ}
    (h : eventuallyUnionStepStable traj ε N)
    (hN : N ≤ M) :
    eventuallyUnionStepStable traj ε M := by
  intro n hn
  exact h n (Nat.le_trans hN hn)

/-- Uniform step stability implies eventual step stability from any start. -/
theorem eventuallyUnionStepStable_of_unionStepStable
    {traj : ProfileTrajectory α} {ε : ℝ≥0∞} (N : ℕ)
    (h : unionStepStable traj ε) :
    eventuallyUnionStepStable traj ε N := by
  intro n _hn
  exact h n

/-- Temporal divergence between two supplied trajectories, witnessed by a time
    at which their profile states are not equal. -/
structure DivergentTrajectories
    (ctx : AgencyContext α Act) (traj₁ traj₂ : ProfileTrajectory α) where
  /-- Time at which the trajectories differ. -/
  divergenceTime : ℕ
  /-- Profile states differ at the divergence time. -/
  branch_diff :
    traj₁.profileAt divergenceTime ≠ traj₂.profileAt divergenceTime

/-- One-step branch profile from an initial profile and an action. -/
def oneStepBranch (ctx : AgencyContext α Act) (P : ScalarProfile α) (a : Act) :
    ScalarProfile α :=
  branchProfile ctx P a

/-- A free-will witness supplies live feasible actions whose future contents
    differ. This is the temporal-trajectory naming bridge for the existing
    branch-sensitive witness data. -/
theorem freeWillWitness_live_branch_contents_distinct
    {ctx : AgencyContext α Act} {P : ScalarProfile α}
    (w : FreeWillWitness ctx P) :
    ∃ selected alternative,
      liveAlternative ctx P selected alternative ∧
        branchFutureContents ctx P selected ≠
          branchFutureContents ctx P alternative :=
  ⟨w.selected, w.alternative, w.alternative_live, w.branch_distinct⟩

/-- One-step branch futures from the selected and alternative actions of a
    free-will witness are distinct. -/
theorem freeWillWitness_oneStep_branch_contents_distinct
    {ctx : AgencyContext α Act} {P : ScalarProfile α}
    (w : FreeWillWitness ctx P) :
    branchFutureContents ctx P w.selected ≠
      branchFutureContents ctx P w.alternative :=
  w.branch_distinct

/-- A PCE-differentiated free-will witness gives the same one-step
    branch-future distinction through its induced `FreeWillWitness`. -/
theorem pceFreeWillWitness_oneStep_branch_contents_distinct
    {ctx : AgencyContext α Act} {P : ScalarProfile α}
    (w : PCEFreeWillWitness ctx P) :
    branchFutureContents ctx P w.selected ≠
      branchFutureContents ctx P w.alternative :=
  (w.toFreeWillWitness).branch_distinct

/-- Deferred marker: stochastic trajectory models are not formalized in this
    deterministic trajectory layer. This is not a theorem claim. -/
def stochasticTrajectory_deferred : Prop := True

/-- Deferred marker: phenomenological duration is not formalized in this
    deterministic trajectory layer. This is not a theorem claim. -/
def phenomenologicalDuration_deferred : Prop := True

/-- Deferred marker: a richer temporal-continuity metric remains future work.
    This is not a theorem claim. -/
def temporalContinuityMetric_deferred : Prop := True

end TLICA.TemporalTrajectory
